version: '3'

services:

  traefik:
    image: traefik:v2.2
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - ./config/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock:ro

  app:
    image: ghost
    ports:
      - "2368:2368"
    volumes:
      - static_files:/app/static/
      - media_files:/app/media/
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.routers.app-http.entrypoints=web"
      - "traefik.http.routers.app-http.rule=Host(`${HOST:-localhost}`)"
      - "traefik.http.routers.app-https.entrypoints=websecure"
      - "traefik.http.routers.app-https.rule=Host(`${HOST:-localhost}`)"
      - "traefik.http.routers.app-https.tls.certresolver=CertificateResolver0"

  nginx:
    image: nginx:alpine
    links:
      - app:app
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/static
      - media_files:/media
    labels:
       - "traefik.enable=true"
       - "traefik.backend=nginx"
       - "traefik.port=9000"
       - "traefik.http.routers.static-http.entrypoints=web"
       - "traefik.http.routers.static-http.rule=Host(`${HOST:-localhost}`) && PathPrefix(`/static`) || PathPrefix(`/media`)"
       - "traefik.http.routers.static-https.entrypoints=websecure"
       - "traefik.http.routers.static-https.rule=Host(`${HOST:-localhost}`) && PathPrefix(`/static`) || PathPrefix(`/media`)"
       - "traefik.http.routers.static-https.tls.certresolver=CertificateResolver0"
    ports:
     - "9000:9000"

volumes:
  static_files:
  media_files:
